FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y lftp kpartx qemu-utils git debootstrap \
    python3 python3-dev python3-pip lsb-release sudo curl gdisk \
    dosfstools
RUN python3 -m pip install diskimage-builder

WORKDIR /octavia/diskimage-create
ENV CLOUD_INIT_DATASOURCES="ConfigDrive, OpenStack"

CMD ./diskimage-create.sh -a arm64 -i ubuntu-minimal -s 2 -d focal
